spring.application.name=activityservice
spring.data.mongodb.uri=mongodb://localhost:27017/aiactivityfitness
spring.data.mongodb.database=aiactivityfitness
spring.eureka.client.service-url.defaultZone=http://localhost:8761/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.name=activity-events

server.port=8082

# Disable Spring Cloud Config
spring.cloud.config.enabled=false

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

