spring:

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/airecommendationfitness}
      database: ${MONGO_DATABASE:airecommendationfitness}

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:activity-processor-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

cloud:
  config:
    enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}

kafka:
  topic:
    name: ${KAFKA_TOPIC_NAME:activity-events}

server:
  port: ${SERVER_PORT:8083}

gemini:
  api:
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
    key: ${GEMINI_KEY}
